### ISSUE TITLE
AttributeError: module 'mistune' has no attribute '_pre_tags'

### ISSUE THREAD

**Issue by maradanasai** [DMOJ/online-judge#1831]
I followed the documentation and executed the steps as mentioned. I'm getting following error
I'm using Ubuntu 20.4 OS

`sai@sai:~/site$ python3 manage.py check
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/template/utils.py", line 66, in __getitem__
    return self._engines[alias]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.8/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/dist-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rajeev/site/judge/admin/__init__.py", line 5, in <module>
    from judge.admin.comments import CommentAdmin
  File "/home/rajeev/site/judge/admin/comments.py", line 8, in <module>
    from judge.widgets import AdminHeavySelect2Widget, AdminMartorWidget
  File "/home/rajeev/site/judge/widgets/__init__.py", line 3, in <module>
    from judge.widgets.mixins import CompressorWidgetMixin
  File "/home/rajeev/site/judge/widgets/mixins.py", line 9, in <module>
    class CompressorWidgetMixin(object):
  File "/home/rajeev/site/judge/widgets/mixins.py", line 23, in CompressorWidgetMixin
    (False, False): Template(''),
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 149, in __init__
    engine = Engine.get_default()
  File "/usr/local/lib/python3.8/dist-packages/django/template/engine.py", line 76, in get_default
    for engine in engines.all():
  File "/usr/local/lib/python3.8/dist-packages/django/template/utils.py", line 90, in all
    return [self[alias] for alias in self]
  File "/usr/local/lib/python3.8/dist-packages/django/template/utils.py", line 90, in <listcomp>
    return [self[alias] for alias in self]
  File "/usr/local/lib/python3.8/dist-packages/django/template/utils.py", line 81, in __getitem__
    engine = engine_cls(params)
  File "/usr/local/lib/python3.8/dist-packages/django_jinja/backend.py", line 188, in __init__
    self.env = environment_cls(**options)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 362, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 118, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/usr/local/lib/python3.8/dist-packages/jinja2/utils.py", line 215, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
  File "/home/rajeev/site/judge/jinja2/__init__.py", line 11, in <module>
    from . import (camo, datetime, filesize, gravatar, language, markdown, rating, reference, render, social,
  File "/home/rajeev/site/judge/jinja2/markdown/__init__.py", line 14, in <module>
    from judge.jinja2.markdown.math import MathInlineGrammar, MathInlineLexer, MathRenderer
  File "/home/rajeev/site/judge/jinja2/markdown/math.py", line 7, in <module>
    mistune._pre_tags.append('latex')
AttributeError: module 'mistune' has no attribute '_pre_tags'
sai@sai:~/site$`

**Comment by ckan719** [comment]
hi, i had the same problem, how did you solve it

**Comment by thecodersatish** [comment]
Use mistune 0.8.0 it will solve your problem

**Comment by fluix-dev** [comment]
For posterity, this was fixed some time ago in https://github.com/DMOJ/online-judge/commit/0975d4d00ed58c9da888e0fcc3f9acdf5d66c48a.
