### ISSUE TITLE
Getting Internal Error while submitting

### ISSUE THREAD

**Issue by thecodersatish** [DMOJ/online-judge#1834]
While submitting I'm getting the following error 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dmoj/judge.py", line 404, in _worker_process_main
    ipc_msg = next(case_gen)
  File "/usr/local/lib/python3.7/dist-packages/dmoj/judge.py", line 439, in _grade_cases
   self.submission.problem_id,self.submission.time_limit, self.submission.memory_limit, self.submission.meta
  File "/usr/local/lib/python3.7/dist-packages/dmoj/problem.py", line 38, in __init__
    self.config = ProblemConfig(self.problem_data, meta)
  File "/usr/local/lib/python3.7/dist-packages/dmoj/problem.py", line 204, in __init__
    raise InvalidInitException('I find your lack of content disturbing.')
dmoj.config.InvalidInitException: I find your lack of content disturbing.

**Comment by thecodersatish** [comment]
Please help me on this

**Comment by kiritofeng** [comment]
You need to fill in the `init.yml`.

**Comment by thecodersatish** [comment]
What to be in init.yml
I mean provide any example

**Comment by kiritofeng** [comment]
We have [examples in the docs](https://github.com/DMOJ/docs/tree/master/problem_examples).

**Comment by thecodersatish** [comment]
I'm adding testcase in the edit test data but those are not adding to the init.yml
