### ISSUE TITLE
TimeZone error? 

### ISSUE THREAD

**Issue by duongnotnhan** [DMOJ/online-judge#2261]
![image](https://github.com/DMOJ/online-judge/assets/98535924/330cf645-7b6a-4e69-8d80-64989217f4a1)
I don't know how to fix this problem?

**Comment by duongnotnhan** [comment]
`Environment:


Request Method: GET
Request URL: http://0.0.0.0:8000/admin/judge/problem/

Django Version: 3.2.19
Python Version: 3.10.6
Installed Applications:
('wpadmin',
 'django.contrib.admin',
 'judge',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.flatpages',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.redirects',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django.contrib.sitemaps',
 'registration',
 'mptt',
 'reversion',
 'django_social_share',
 'social_django',
 'compressor',
 'django_ace',
 'pagedown',
 'sortedm2m',
 'statici18n',
 'impersonate',
 'django_jinja',
 'martor',
 'adminsortable2')
Installed Middleware:
('judge.middleware.ShortCircuitMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'judge.middleware.APIMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'judge.middleware.DMOJLoginMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'judge.user_log.LogUserAccessMiddleware',
 'judge.timezone.TimezoneMiddleware',
 'impersonate.middleware.ImpersonateMiddleware',
 'judge.middleware.DMOJImpersonationMiddleware',
 'judge.middleware.ContestMiddleware',
 'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
 'judge.social_auth.SocialAuthExceptionMiddleware',
 'django.contrib.redirects.middleware.RedirectFallbackMiddleware')


Template error:
In template /home/duongnhanac/dnaoj/lib/python3.10/site-packages/wpadmin/templates/admin/base.html, error at line 51
   Database returned an invalid datetime value. Are time zone definitions for your database installed?
   41 : 	window.__wpadmin_cookie_name = 'djangoWpAdminSettings';
   42 : 
   43 : 	// we need jQuery in default namespace (not django.jQuery) because we use some external jQuery plugins
   44 : 	if (typeof jQuery == 'undefined') {
   45 : 		// we can get jQuery object from django object but there are some admin templates where jQuery is not loaded
   46 : 		if (typeof django == 'undefined' || typeof django.jQuery == 'undefined') {
   47 : 			// so lets load our jQuery synchronously
   48 : 			document.write(decodeURI("%3Cscript src='{% static "wpadmin/js/lib/jquery.min.js" %}' type='text/javascript'%3E%3C/script%3E"));
   49 : 		} else {
   50 : 			// lest copy jQuery from django object to default namespace
   51 : 			window .jQuery = django.jQuery ;
   52 : 		}
   53 : 	}
   54 : </script>
   55 : <script type="text/javascript" src="{% static "wpadmin/js/lib/jquery.cookie.min.js" %}"></script>
   56 : <script type="text/javascript" src="{% static "wpadmin/js/menus.js" %}"></script>
   57 : <script type="text/javascript" src="{% static "wpadmin/js/content.js" %}"></script>
   58 : <link rel="stylesheet" type="text/css" href="{% static "wpadmin/css/wpadmin.site.css" %}" />
   59 : {# WP Admin end #}
   60 : {% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
   61 : </head>


Traceback (most recent call last):
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 379, in date_hierarchy
    'choices': [{
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/db/models/query.py", line 171, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1122, in apply_converters
    value = converter(value, expression, connection)
  File "/home/duongnhanac/dnaoj/lib/python3.10/site-packages/django/db/models/functions/datetime.py", line 252, in convert_value
    raise ValueError(

Exception Type: ValueError at /admin/judge/problem/
Exception Value: Database returned an invalid datetime value. Are time zone definitions for your database installed?
`

**Comment by Ninjaclasher** [comment]
You probably want to install time zone definitions (https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html)
